EXTRAFLAGS = 

PACKAGE = bblock

CPPSRCS = bblock.cc # add your other .cc files here

CPPHDRS = bblock.h BasicBlock.h # add your other .h files here 

OTHERSRCS = Makefile 

include ../config/Rules.make
